site_name: Alpino & Universal Dependencies

theme:
    name: material
    language: nl
    palette:
        primary: blue grey
    #favicon: favicon.ico
    #logo: favicon.png
    features:
        - navigation.tabs

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.caret
    - pymdownx.highlight
    - pymdownx.superfences
    - toc:
        permalink: true
        toc_depth: 4

plugins:
    - search:
        lang: nl

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/rug-compling/alud-docs
          name: This documentation on GitHub

nav:
    - 'Introduction': 'index.md'
    - 'Cookbook Alpino': 'alpino.md'
    - 'Cookbook UD': 'ud.md'
    - 'Cookbook Alpino + UD': 'alpinoud.md'
    - 'Links': 'links.md'
